<?php
/**
 * @file
 * Code for the HOT Core feature.
 */

include_once 'hot_core.features.inc';


/**
 * Implements hook_menu_alter()
 */
function hot_core_menu_alter(&$items) {
    // Disable the page node
    $items['node'] = array(
      'page callback' => 'hot_core_front_page',
      'access callback' => TRUE,
    );
    $items['taxonomy/term/%taxonomy_term']['page callback'] = 'drupal_not_found';
    $items['taxonomy/term/%taxonomy_term/view']['page callback'] = 'drupal_not_found';
    $items['taxonomy/term/%taxonomy_term/feed']['page callback'] = 'drupal_not_found';
}

function hot_core_front_page() {
  return '';
}

function hot_core_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'mailchimp_signup_subscribe_block_hot_newsletter_form') {
      unset($form['mergevars']['EMAIL']['#title']);
      $form['mergevars']['EMAIL']['#attributes'] = array('placeholder' => t('signup@example.com'));
      $form['mergevars']['EMAIL']['#size'] = 12;
  }
}

/**
 * Implements hook_menu_block_blocks().
 */
function hot_core_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'hot_core-1' => array(
      'parent'      => 'main-menu:0',
      'title_link'  => 0,
      'admin_title' => 'Main navigation: First level',
      'level'       => 1,
      'follow'      => '0',
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'hot_core-2' => array(
      'parent'      => 'main-menu:0',
      'title_link'  => 0,
      'admin_title' => 'Main navigation: Second level',
      'level'       => 2,
      'follow'      => '0',
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'hot_core-3' => array(
      'parent'      => 'main-menu:0',
      'title_link'  => 0,
      'admin_title' => 'Main navigation: Third level',
      'level'       => 3,
      'follow'      => '0',
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}


/**
 * Implements hook_responsive_menus_styles_alter().
 */
function hot_core_responsive_menus_styles_alter(&$styles) {
  // Use Sidr's 'light' theme instead of 'dark'
  $styles['sidr']['css_files'] = array(libraries_get_path('sidr') . '/stylesheets/jquery.sidr.light.css');
}
