<?php

/**
 * @file
 * Install, update and uninstall functions for the Variable API extended test
 * module.
 */

/**
 * Implements hook_install().
 */
function vars_extended_test_install() {
  $vars = new VarsExtendedTestVars();
  $vars->saveDefaults();
}

/**
 * Implements hook_uninstall().
 */
function vars_extended_test_uninstall() {
  $vars = new VarsExtendedTestVars();
  $vars->removeDefaults();
}
