<?php

include_once('hot_front.features.inc');


/**
 * Implements hook_menu_alter()
 */
function hot_front_menu() {
  // Disable the page node
  $items['front'] = array(
    'page callback' => 'hot_front_page',
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_menu_alter()
 */
function hot_front_menu_alter(&$items) {
  // Disable the page node
  $items['node']['access callback'] = FALSE;
}

function hot_front_page() {
  return "";
}
