name = Hotty
description = A simple 2 column layout special for HOT.
preview = preview.png
template = hotty-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar]        = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/hotty/hotty.layout.css
