name = HOT Layout
description = Layout for HOT
preview = preview.png
template = hot-layout-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[follow]         = After content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/hot-layout/hot-layout.layout.css
stylesheets[all][] = css/layouts/hot-layout/hot-layout.layout.no-query.css
