<?php

function views_enhanced_block_views_api() {
  return array(
    'api' => 3,
  );
}

function views_enhanced_block_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  // Remove the more link from view if displayed in block title
  $block_title = $view->display_handler->get_option('block_title');
  if (isset($variables['more']) && $block_title['more_link'] == 1) {
    $variables['more'] = '';
  }
  // Remove the feed icon from view if displayed in block title
  if (isset($variables['feed_icon']) && $block_title['feed_icon'] == 1) {
    $variables['feed_icon'] = '';
  }
}
