name = Ohm Hero
description = A 3 column layout with a prominent hero region.
preview = preview.png
template = ohm-hero-layout

; Regions
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/ohm-hero/ohm-hero-layout.css
